### ISSUE TITLE
Createbuffer command ignores color parameter

### ISSUE THREAD

**Issue by IRA1777** [minetest-mirrors/digistuff#2]
Background color of a buffer is always black, whatever the color parameter was set on.

**Comment by OgelGames** [comment]
This is not the correct place to report issues, this is a mirror of https://cheapiesystems.com/git/digistuff. We also have our own active fork at https://github.com/mt-mods/digistuff, which can be used to report issues.

I can solve your issue though, and the problem is the documentation, which incorrectly shows a `color` parameter, when it should actually be `fill`.

This works as expected:
```lua
digiline_send("gpu", {
	command = "createbuffer",
	buffer = 0,
	xsize = 16,
	ysize = 2,
	fill = "aaaaaa",
})
```

**Comment by IRA1777** [comment]
Ok, thx, I'll report it at the right place.
